// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome2 = Welcome2.FromJson(jsonString);
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

namespace Entity.Response
{

    public partial class PlayerResponse
    {
        public ResponseContext ResponseContext { get; set; }

        public PlayabilityStatus PlayabilityStatus { get; set; }

        public StreamingData StreamingData { get; set; }

        public PlayerAd[] PlayerAds { get; set; }

        public PlaybackTracking PlaybackTracking { get; set; }

        public VideoDetails VideoDetails { get; set; }

        public Annotation[] Annotations { get; set; }

        public PlayerConfig PlayerConfig { get; set; }

        public Storyboards Storyboards { get; set; }

        public Microformat Microformat { get; set; }

        public Cards Cards { get; set; }

        public string TrackingParams { get; set; }

        public Attestation Attestation { get; set; }

        public Message[] Messages { get; set; }

        public Endscreen Endscreen { get; set; }

        public AdPlacement[] AdPlacements { get; set; }
    }

    public partial class AdPlacement
    {
        [JsonProperty("adPlacementRenderer")]
        public AdPlacementRenderer AdPlacementRenderer { get; set; }
    }

    public partial class AdPlacementRenderer
    {
        [JsonProperty("config")]
        public Config Config { get; set; }

        [JsonProperty("renderer")]
        public Renderer Renderer { get; set; }

        [JsonProperty("adSlotLoggingData", NullValueHandling = NullValueHandling.Ignore)]
        public AdSlotLoggingData AdSlotLoggingData { get; set; }
    }

    public partial class AdSlotLoggingData
    {
        [JsonProperty("serializedSlotAdServingDataEntry")]
        public string SerializedSlotAdServingDataEntry { get; set; }
    }

    public partial class Config
    {
        [JsonProperty("adPlacementConfig")]
        public AdPlacementConfig AdPlacementConfig { get; set; }
    }

    public partial class AdPlacementConfig
    {
        [JsonProperty("kind")]
        public string Kind { get; set; }

        [JsonProperty("adTimeOffset")]
        public AdTimeOffset AdTimeOffset { get; set; }

        [JsonProperty("hideCueRangeMarker")]
        public bool HideCueRangeMarker { get; set; }
    }

    public partial class AdTimeOffset
    {
        [JsonProperty("offsetStartMilliseconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long OffsetStartMilliseconds { get; set; }

        [JsonProperty("offsetEndMilliseconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long OffsetEndMilliseconds { get; set; }
    }

    public partial class Renderer
    {
        [JsonProperty("clientForecastingAdRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public ClientForecastingAdRenderer ClientForecastingAdRenderer { get; set; }

        [JsonProperty("adBreakServiceRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public AdBreakServiceRenderer AdBreakServiceRenderer { get; set; }
    }

    public partial class AdBreakServiceRenderer
    {
        [JsonProperty("prefetchMilliseconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long PrefetchMilliseconds { get; set; }

        [JsonProperty("getAdBreakUrl")]
        public Uri GetAdBreakUrl { get; set; }
    }

    public partial class ClientForecastingAdRenderer
    {
        [JsonProperty("impressionUrls")]
        public PtrackingUrlElement[] ImpressionUrls { get; set; }
    }

    public partial class PtrackingUrlElement
    {
        [JsonProperty("baseUrl")]
        public Uri BaseUrl { get; set; }
    }

    public partial class Annotation
    {
        [JsonProperty("playerAnnotationsExpandedRenderer")]
        public PlayerAnnotationsExpandedRenderer PlayerAnnotationsExpandedRenderer { get; set; }
    }

    public partial class PlayerAnnotationsExpandedRenderer
    {
        [JsonProperty("featuredChannel")]
        public FeaturedChannel FeaturedChannel { get; set; }

        [JsonProperty("allowSwipeDismiss")]
        public bool AllowSwipeDismiss { get; set; }

        [JsonProperty("annotationId")]
        public Guid AnnotationId { get; set; }
    }

    public partial class FeaturedChannel
    {
        [JsonProperty("startTimeMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StartTimeMs { get; set; }

        [JsonProperty("endTimeMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long EndTimeMs { get; set; }

        [JsonProperty("watermark")]
        public WatermarkClass Watermark { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("navigationEndpoint")]
        public NavigationEndpoint NavigationEndpoint { get; set; }

        [JsonProperty("channelName")]
        public string ChannelName { get; set; }

        [JsonProperty("subscribeButton")]
        public SubscribeButtonClass SubscribeButton { get; set; }
    }

    public partial class NavigationEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("browseEndpoint")]
        public BrowseEndpoint BrowseEndpoint { get; set; }
    }

    public partial class BrowseEndpoint
    {
        [JsonProperty("browseId")]
        public string BrowseId { get; set; }
    }

    public partial class SubscribeButtonClass
    {
        [JsonProperty("subscribeButtonRenderer")]
        public SubscribeButtonRenderer SubscribeButtonRenderer { get; set; }
    }

    public partial class SubscribeButtonRenderer
    {
        [JsonProperty("buttonText")]
        public MessageTitle ButtonText { get; set; }

        [JsonProperty("subscribed")]
        public bool Subscribed { get; set; }

        [JsonProperty("enabled")]
        public bool Enabled { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("channelId")]
        public string ChannelId { get; set; }

        [JsonProperty("showPreferences")]
        public bool ShowPreferences { get; set; }

        [JsonProperty("subscribedButtonText")]
        public MessageTitle SubscribedButtonText { get; set; }

        [JsonProperty("unsubscribedButtonText")]
        public MessageTitle UnsubscribedButtonText { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("unsubscribeButtonText")]
        public MessageTitle UnsubscribeButtonText { get; set; }

        [JsonProperty("serviceEndpoints")]
        public ServiceEndpoint[] ServiceEndpoints { get; set; }

        [JsonProperty("signInEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public SigninEndpoint SignInEndpoint { get; set; }
    }

    public partial class MessageTitle
    {
        [JsonProperty("runs")]
        public Run[] Runs { get; set; }
    }

    public partial class Run
    {
        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class ServiceEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("subscribeEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public SubscribeEndpoint SubscribeEndpoint { get; set; }

        [JsonProperty("unsubscribeEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public SubscribeEndpoint UnsubscribeEndpoint { get; set; }
    }

    public partial class SubscribeEndpoint
    {
        [JsonProperty("channelIds")]
        public string[] ChannelIds { get; set; }

        [JsonProperty("params")]
        public string Params { get; set; }
    }

    public partial class SigninEndpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }
    }

    public partial class WatermarkClass
    {
        [JsonProperty("thumbnails")]
        public ThumbnailThumbnail[] Thumbnails { get; set; }
    }

    public partial class ThumbnailThumbnail
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }
    }

    public partial class Attestation
    {
        [JsonProperty("playerAttestationRenderer")]
        public PlayerAttestationRenderer PlayerAttestationRenderer { get; set; }
    }

    public partial class PlayerAttestationRenderer
    {
        [JsonProperty("challenge")]
        public string Challenge { get; set; }

        [JsonProperty("botguardData")]
        public BotguardData BotguardData { get; set; }
    }

    public partial class BotguardData
    {
        [JsonProperty("program")]
        public string Program { get; set; }

        [JsonProperty("interpreterUrl")]
        public string InterpreterUrl { get; set; }
    }

    public partial class Cards
    {
        [JsonProperty("cardCollectionRenderer")]
        public CardCollectionRenderer CardCollectionRenderer { get; set; }
    }

    public partial class CardCollectionRenderer
    {
        [JsonProperty("cards")]
        public Card[] Cards { get; set; }

        [JsonProperty("headerText")]
        public HeaderText HeaderText { get; set; }

        [JsonProperty("icon")]
        public CloseButton Icon { get; set; }

        [JsonProperty("closeButton")]
        public CloseButton CloseButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("allowTeaserDismiss")]
        public bool AllowTeaserDismiss { get; set; }

        [JsonProperty("logIconVisibilityUpdates")]
        public bool LogIconVisibilityUpdates { get; set; }
    }

    public partial class Card
    {
        [JsonProperty("cardRenderer")]
        public CardRenderer CardRenderer { get; set; }
    }

    public partial class CardRenderer
    {
        [JsonProperty("teaser")]
        public Teaser Teaser { get; set; }

        [JsonProperty("content")]
        public Content Content { get; set; }

        [JsonProperty("cueRanges")]
        public CueRange[] CueRanges { get; set; }

        [JsonProperty("icon")]
        public CloseButton Icon { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("cardId")]
        public Guid CardId { get; set; }

        [JsonProperty("feature")]
        public string Feature { get; set; }
    }

    public partial class Content
    {
        [JsonProperty("videoInfoCardContentRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public VideoInfoCardContentRenderer VideoInfoCardContentRenderer { get; set; }

        [JsonProperty("simpleCardContentRenderer", NullValueHandling = NullValueHandling.Ignore)]
        public SimpleCardContentRenderer SimpleCardContentRenderer { get; set; }
    }

    public partial class SimpleCardContentRenderer
    {
        [JsonProperty("image")]
        public WatermarkClass Image { get; set; }

        [JsonProperty("title")]
        public HeaderText Title { get; set; }

        [JsonProperty("actionButton")]
        public ActionButton ActionButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("displayDomain")]
        public HeaderText DisplayDomain { get; set; }

        [JsonProperty("showLinkIcon")]
        public bool ShowLinkIcon { get; set; }

        [JsonProperty("callToAction")]
        public HeaderText CallToAction { get; set; }

        [JsonProperty("command")]
        public CommandClass Command { get; set; }
    }

    public partial class ActionButton
    {
        [JsonProperty("simpleCardButtonRenderer")]
        public SimpleCardButtonRenderer SimpleCardButtonRenderer { get; set; }
    }

    public partial class SimpleCardButtonRenderer
    {
        [JsonProperty("text")]
        public HeaderText Text { get; set; }

        [JsonProperty("action")]
        public CommandClass Action { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class CommandClass
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("urlEndpoint")]
        public UrlEndpoint UrlEndpoint { get; set; }
    }

    public partial class UrlEndpoint
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("target")]
        public string Target { get; set; }
    }

    public partial class HeaderText
    {
        [JsonProperty("simpleText", NullValueHandling = NullValueHandling.Ignore)]
        public string SimpleText { get; set; }
    }

    public partial class VideoInfoCardContentRenderer
    {
        [JsonProperty("videoThumbnail")]
        public WatermarkClass VideoThumbnail { get; set; }

        [JsonProperty("lengthString")]
        public Title LengthString { get; set; }

        [JsonProperty("videoTitle")]
        public HeaderText VideoTitle { get; set; }

        [JsonProperty("channelName")]
        public HeaderText ChannelName { get; set; }

        [JsonProperty("viewCountText")]
        public HeaderText ViewCountText { get; set; }

        [JsonProperty("action")]
        public VideoInfoCardContentRendererAction Action { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("customMessage")]
        public HeaderText CustomMessage { get; set; }
    }

    public partial class VideoInfoCardContentRendererAction
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("watchEndpoint")]
        public ActionWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class ActionWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }
    }

    public partial class Title
    {
        [JsonProperty("accessibility")]
        public Accessibility Accessibility { get; set; }

        [JsonProperty("simpleText")]
        public string SimpleText { get; set; }
    }

    public partial class Accessibility
    {
        [JsonProperty("accessibilityData")]
        public AccessibilityData AccessibilityData { get; set; }
    }

    public partial class AccessibilityData
    {
        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class CueRange
    {
        [JsonProperty("startCardActiveMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StartCardActiveMs { get; set; }

        [JsonProperty("endCardActiveMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long EndCardActiveMs { get; set; }

        [JsonProperty("teaserDurationMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long TeaserDurationMs { get; set; }

        [JsonProperty("iconAfterTeaserMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IconAfterTeaserMs { get; set; }
    }

    public partial class CloseButton
    {
        [JsonProperty("infoCardIconRenderer")]
        public InfoCardIconRenderer InfoCardIconRenderer { get; set; }
    }

    public partial class InfoCardIconRenderer
    {
        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Teaser
    {
        [JsonProperty("simpleCardTeaserRenderer")]
        public SimpleCardTeaserRenderer SimpleCardTeaserRenderer { get; set; }
    }

    public partial class SimpleCardTeaserRenderer
    {
        [JsonProperty("message")]
        public HeaderText Message { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("prominent")]
        public bool Prominent { get; set; }

        [JsonProperty("logVisibilityUpdates")]
        public bool LogVisibilityUpdates { get; set; }
    }

    public partial class Endscreen
    {
        [JsonProperty("endscreenRenderer")]
        public EndscreenRenderer EndscreenRenderer { get; set; }
    }

    public partial class EndscreenRenderer
    {
        [JsonProperty("elements")]
        public Element[] Elements { get; set; }

        [JsonProperty("startMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StartMs { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class Element
    {
        [JsonProperty("endscreenElementRenderer")]
        public EndscreenElementRenderer EndscreenElementRenderer { get; set; }
    }

    public partial class EndscreenElementRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("image")]
        public WatermarkClass Image { get; set; }

        [JsonProperty("icon", NullValueHandling = NullValueHandling.Ignore)]
        public Icon Icon { get; set; }

        [JsonProperty("left")]
        public double Left { get; set; }

        [JsonProperty("width")]
        public double Width { get; set; }

        [JsonProperty("top")]
        public double Top { get; set; }

        [JsonProperty("aspectRatio")]
        public double AspectRatio { get; set; }

        [JsonProperty("startMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long StartMs { get; set; }

        [JsonProperty("endMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long EndMs { get; set; }

        [JsonProperty("title")]
        public Title Title { get; set; }

        [JsonProperty("metadata")]
        public HeaderText Metadata { get; set; }

        [JsonProperty("callToAction", NullValueHandling = NullValueHandling.Ignore)]
        public HeaderText CallToAction { get; set; }

        [JsonProperty("dismiss", NullValueHandling = NullValueHandling.Ignore)]
        public HeaderText Dismiss { get; set; }

        [JsonProperty("endpoint")]
        public Endpoint Endpoint { get; set; }

        [JsonProperty("hovercardButton", NullValueHandling = NullValueHandling.Ignore)]
        public SubscribeButtonClass HovercardButton { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("isSubscribe", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsSubscribe { get; set; }

        [JsonProperty("signinEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public SigninEndpoint SigninEndpoint { get; set; }

        [JsonProperty("useClassicSubscribeButton", NullValueHandling = NullValueHandling.Ignore)]
        public bool? UseClassicSubscribeButton { get; set; }

        [JsonProperty("id")]
        public Guid Id { get; set; }

        [JsonProperty("playlistLength", NullValueHandling = NullValueHandling.Ignore)]
        public HeaderText PlaylistLength { get; set; }

        [JsonProperty("videoDuration", NullValueHandling = NullValueHandling.Ignore)]
        public HeaderText VideoDuration { get; set; }
    }

    public partial class Endpoint
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("browseEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public BrowseEndpoint BrowseEndpoint { get; set; }

        [JsonProperty("watchEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public EndpointWatchEndpoint WatchEndpoint { get; set; }
    }

    public partial class EndpointWatchEndpoint
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("playlistId", NullValueHandling = NullValueHandling.Ignore)]
        public string PlaylistId { get; set; }
    }

    public partial class Icon
    {
        [JsonProperty("thumbnails")]
        public IconThumbnail[] Thumbnails { get; set; }
    }

    public partial class IconThumbnail
    {
        [JsonProperty("url")]
        public Uri Url { get; set; }
    }

    public partial class Message
    {
        [JsonProperty("mealbarPromoRenderer")]
        public MealbarPromoRenderer MealbarPromoRenderer { get; set; }
    }

    public partial class MealbarPromoRenderer
    {
        [JsonProperty("messageTexts")]
        public MessageTitle[] MessageTexts { get; set; }

        [JsonProperty("actionButton")]
        public ActionButtonClass ActionButton { get; set; }

        [JsonProperty("dismissButton")]
        public ActionButtonClass DismissButton { get; set; }

        [JsonProperty("triggerCondition")]
        public string TriggerCondition { get; set; }

        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }

        [JsonProperty("impressionEndpoints")]
        public ImpressionEndpointElement[] ImpressionEndpoints { get; set; }

        [JsonProperty("isVisible")]
        public bool IsVisible { get; set; }

        [JsonProperty("messageTitle")]
        public MessageTitle MessageTitle { get; set; }
    }

    public partial class ActionButtonClass
    {
        [JsonProperty("buttonRenderer")]
        public ButtonRenderer ButtonRenderer { get; set; }
    }

    public partial class ButtonRenderer
    {
        [JsonProperty("style")]
        public string Style { get; set; }

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("text")]
        public MessageTitle Text { get; set; }

        [JsonProperty("serviceEndpoint")]
        public ImpressionEndpointElement ServiceEndpoint { get; set; }

        [JsonProperty("navigationEndpoint", NullValueHandling = NullValueHandling.Ignore)]
        public CommandClass NavigationEndpoint { get; set; }

        [JsonProperty("trackingParams")]
        public string TrackingParams { get; set; }
    }

    public partial class ImpressionEndpointElement
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("feedbackEndpoint")]
        public FeedbackEndpoint FeedbackEndpoint { get; set; }
    }

    public partial class FeedbackEndpoint
    {
        [JsonProperty("feedbackToken")]
        public string FeedbackToken { get; set; }

        [JsonProperty("uiActions")]
        public UiActions UiActions { get; set; }
    }

    public partial class UiActions
    {
        [JsonProperty("hideEnclosingContainer")]
        public bool HideEnclosingContainer { get; set; }
    }

    public partial class Microformat
    {
        [JsonProperty("playerMicroformatRenderer")]
        public PlayerMicroformatRenderer PlayerMicroformatRenderer { get; set; }
    }

    public partial class PlayerMicroformatRenderer
    {
        [JsonProperty("thumbnail")]
        public WatermarkClass Thumbnail { get; set; }

        [JsonProperty("embed")]
        public Embed Embed { get; set; }

        [JsonProperty("title")]
        public HeaderText Title { get; set; }

        [JsonProperty("description")]
        public HeaderText Description { get; set; }

        [JsonProperty("lengthSeconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long LengthSeconds { get; set; }

        [JsonProperty("ownerProfileUrl")]
        public Uri OwnerProfileUrl { get; set; }

        [JsonProperty("externalChannelId")]
        public string ExternalChannelId { get; set; }

        [JsonProperty("isFamilySafe")]
        public bool IsFamilySafe { get; set; }

        [JsonProperty("availableCountries")]
        public string[] AvailableCountries { get; set; }

        [JsonProperty("isUnlisted")]
        public bool IsUnlisted { get; set; }

        [JsonProperty("hasYpcMetadata")]
        public bool HasYpcMetadata { get; set; }

        [JsonProperty("viewCount")]
        public string ViewCount { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("publishDate")]
        public DateTimeOffset PublishDate { get; set; }

        [JsonProperty("ownerChannelName")]
        public string OwnerChannelName { get; set; }

        [JsonProperty("uploadDate")]
        public DateTimeOffset UploadDate { get; set; }
    }

    public partial class Embed
    {
        [JsonProperty("iframeUrl")]
        public Uri IframeUrl { get; set; }

        [JsonProperty("flashUrl")]
        public Uri FlashUrl { get; set; }

        [JsonProperty("width")]
        public long Width { get; set; }

        [JsonProperty("height")]
        public long Height { get; set; }

        [JsonProperty("flashSecureUrl")]
        public Uri FlashSecureUrl { get; set; }
    }

    public partial class PlayabilityStatus
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("playableInEmbed")]
        public bool PlayableInEmbed { get; set; }

        [JsonProperty("contextParams")]
        public string ContextParams { get; set; }
    }

    public partial class PlaybackTracking
    {
        [JsonProperty("videostatsPlaybackUrl")]
        public PtrackingUrlElement VideostatsPlaybackUrl { get; set; }

        [JsonProperty("videostatsDelayplayUrl")]
        public PtrackingUrlElement VideostatsDelayplayUrl { get; set; }

        [JsonProperty("videostatsWatchtimeUrl")]
        public PtrackingUrlElement VideostatsWatchtimeUrl { get; set; }

        [JsonProperty("ptrackingUrl")]
        public PtrackingUrlElement PtrackingUrl { get; set; }

        [JsonProperty("qoeUrl")]
        public PtrackingUrlElement QoeUrl { get; set; }

        [JsonProperty("setAwesomeUrl")]
        public AtrUrlClass SetAwesomeUrl { get; set; }

        [JsonProperty("atrUrl")]
        public AtrUrlClass AtrUrl { get; set; }

        [JsonProperty("youtubeRemarketingUrl")]
        public AtrUrlClass YoutubeRemarketingUrl { get; set; }

        [JsonProperty("googleRemarketingUrl")]
        public AtrUrlClass GoogleRemarketingUrl { get; set; }
    }

    public partial class AtrUrlClass
    {
        [JsonProperty("baseUrl")]
        public Uri BaseUrl { get; set; }

        [JsonProperty("elapsedMediaTimeSeconds")]
        public long ElapsedMediaTimeSeconds { get; set; }
    }

    public partial class PlayerAd
    {
        [JsonProperty("playerLegacyDesktopWatchAdsRenderer")]
        public PlayerLegacyDesktopWatchAdsRenderer PlayerLegacyDesktopWatchAdsRenderer { get; set; }
    }

    public partial class PlayerLegacyDesktopWatchAdsRenderer
    {
        [JsonProperty("playerAdParams")]
        public PlayerAdParams PlayerAdParams { get; set; }

        [JsonProperty("gutParams")]
        public GutParams GutParams { get; set; }

        [JsonProperty("showCompanion")]
        public bool ShowCompanion { get; set; }

        [JsonProperty("showInstream")]
        public bool ShowInstream { get; set; }

        [JsonProperty("useGut")]
        public bool UseGut { get; set; }
    }

    public partial class GutParams
    {
        [JsonProperty("tag")]
        public string Tag { get; set; }
    }

    public partial class PlayerAdParams
    {
        [JsonProperty("showContentThumbnail")]
        public bool ShowContentThumbnail { get; set; }

        [JsonProperty("enabledEngageTypes")]
        public string EnabledEngageTypes { get; set; }
    }

    public partial class PlayerConfig
    {
        [JsonProperty("audioConfig")]
        public AudioConfig AudioConfig { get; set; }

        [JsonProperty("streamSelectionConfig")]
        public StreamSelectionConfig StreamSelectionConfig { get; set; }

        [JsonProperty("daiConfig")]
        public DaiConfig DaiConfig { get; set; }

        [JsonProperty("mediaCommonConfig")]
        public MediaCommonConfig MediaCommonConfig { get; set; }

        [JsonProperty("webPlayerConfig")]
        public WebPlayerConfig WebPlayerConfig { get; set; }
    }

    public partial class AudioConfig
    {
        [JsonProperty("loudnessDb")]
        public double LoudnessDb { get; set; }

        [JsonProperty("perceptualLoudnessDb")]
        public double PerceptualLoudnessDb { get; set; }

        [JsonProperty("enablePerFormatLoudness")]
        public bool EnablePerFormatLoudness { get; set; }
    }

    public partial class DaiConfig
    {
        [JsonProperty("enableServerStitchedDai")]
        public bool EnableServerStitchedDai { get; set; }
    }

    public partial class MediaCommonConfig
    {
        [JsonProperty("dynamicReadaheadConfig")]
        public DynamicReadaheadConfig DynamicReadaheadConfig { get; set; }
    }

    public partial class DynamicReadaheadConfig
    {
        [JsonProperty("maxReadAheadMediaTimeMs")]
        public long MaxReadAheadMediaTimeMs { get; set; }

        [JsonProperty("minReadAheadMediaTimeMs")]
        public long MinReadAheadMediaTimeMs { get; set; }

        [JsonProperty("readAheadGrowthRateMs")]
        public long ReadAheadGrowthRateMs { get; set; }
    }

    public partial class StreamSelectionConfig
    {
        [JsonProperty("maxBitrate")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long MaxBitrate { get; set; }
    }

    public partial class WebPlayerConfig
    {
        [JsonProperty("webPlayerActionsPorting")]
        public WebPlayerActionsPorting WebPlayerActionsPorting { get; set; }
    }

    public partial class WebPlayerActionsPorting
    {
        [JsonProperty("getSharePanelCommand")]
        public GetSharePanelCommand GetSharePanelCommand { get; set; }

        [JsonProperty("subscribeCommand")]
        public SubscribeCommand SubscribeCommand { get; set; }

        [JsonProperty("unsubscribeCommand")]
        public UnsubscribeCommand UnsubscribeCommand { get; set; }

        [JsonProperty("addToWatchLaterCommand")]
        public AddToWatchLaterCommand AddToWatchLaterCommand { get; set; }

        [JsonProperty("removeFromWatchLaterCommand")]
        public RemoveFromWatchLaterCommand RemoveFromWatchLaterCommand { get; set; }
    }

    public partial class AddToWatchLaterCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public AddToWatchLaterCommandPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class AddToWatchLaterCommandPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public PurpleAction[] Actions { get; set; }
    }

    public partial class PurpleAction
    {
        [JsonProperty("addedVideoId")]
        public string AddedVideoId { get; set; }

        [JsonProperty("action")]
        public string Action { get; set; }
    }

    public partial class GetSharePanelCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("webPlayerShareEntityServiceEndpoint")]
        public WebPlayerShareEntityServiceEndpoint WebPlayerShareEntityServiceEndpoint { get; set; }
    }

    public partial class WebPlayerShareEntityServiceEndpoint
    {
        [JsonProperty("serializedShareEntity")]
        public string SerializedShareEntity { get; set; }
    }

    public partial class RemoveFromWatchLaterCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("playlistEditEndpoint")]
        public RemoveFromWatchLaterCommandPlaylistEditEndpoint PlaylistEditEndpoint { get; set; }
    }

    public partial class RemoveFromWatchLaterCommandPlaylistEditEndpoint
    {
        [JsonProperty("playlistId")]
        public string PlaylistId { get; set; }

        [JsonProperty("actions")]
        public FluffyAction[] Actions { get; set; }
    }

    public partial class FluffyAction
    {
        [JsonProperty("action")]
        public string Action { get; set; }

        [JsonProperty("removedVideoId")]
        public string RemovedVideoId { get; set; }
    }

    public partial class SubscribeCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("subscribeEndpoint")]
        public SubscribeEndpoint SubscribeEndpoint { get; set; }
    }

    public partial class UnsubscribeCommand
    {
        [JsonProperty("clickTrackingParams")]
        public string ClickTrackingParams { get; set; }

        [JsonProperty("unsubscribeEndpoint")]
        public SubscribeEndpoint UnsubscribeEndpoint { get; set; }
    }

    public partial class ResponseContext
    {
        [JsonProperty("serviceTrackingParams")]
        public ServiceTrackingParam[] ServiceTrackingParams { get; set; }
    }

    public partial class ServiceTrackingParam
    {
        [JsonProperty("service")]
        public string Service { get; set; }

        [JsonProperty("params")]
        public Param[] Params { get; set; }
    }

    public partial class Param
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public partial class Storyboards
    {
        [JsonProperty("playerStoryboardSpecRenderer")]
        public PlayerStoryboardSpecRenderer PlayerStoryboardSpecRenderer { get; set; }
    }

    public partial class PlayerStoryboardSpecRenderer
    {
        [JsonProperty("spec")]
        public Uri Spec { get; set; }
    }

    public partial class StreamingData
    {
        [JsonProperty("expiresInSeconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ExpiresInSeconds { get; set; }

        [JsonProperty("formats")]
        public Format[] Formats { get; set; }

        [JsonProperty("adaptiveFormats")]
        public Format[] AdaptiveFormats { get; set; }
    }

    public partial class Format
    {
        [JsonProperty("itag")]
        public long Itag { get; set; }

        [JsonProperty("mimeType")]
        public string MimeType { get; set; }

        [JsonProperty("bitrate")]
        public long Bitrate { get; set; }

        [JsonProperty("width", NullValueHandling = NullValueHandling.Ignore)]
        public long? Width { get; set; }

        [JsonProperty("height", NullValueHandling = NullValueHandling.Ignore)]
        public long? Height { get; set; }

        [JsonProperty("initRange", NullValueHandling = NullValueHandling.Ignore)]
        public Range InitRange { get; set; }

        [JsonProperty("indexRange", NullValueHandling = NullValueHandling.Ignore)]
        public Range IndexRange { get; set; }

        [JsonProperty("lastModified")]
        public string LastModified { get; set; }

        [JsonProperty("contentLength")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ContentLength { get; set; }

        [JsonProperty("quality")]
        public string Quality { get; set; }

        [JsonProperty("fps", NullValueHandling = NullValueHandling.Ignore)]
        public long? Fps { get; set; }

        [JsonProperty("qualityLabel", NullValueHandling = NullValueHandling.Ignore)]
        public string QualityLabel { get; set; }

        [JsonProperty("projectionType")]
        public ProjectionType ProjectionType { get; set; }

        [JsonProperty("averageBitrate")]
        public long AverageBitrate { get; set; }

        [JsonProperty("approxDurationMs")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ApproxDurationMs { get; set; }

        [JsonProperty("signatureCipher")]
        public string SignatureCipher { get; set; }

        [JsonProperty("colorInfo", NullValueHandling = NullValueHandling.Ignore)]
        public ColorInfo ColorInfo { get; set; }

        [JsonProperty("highReplication", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HighReplication { get; set; }

        [JsonProperty("audioQuality", NullValueHandling = NullValueHandling.Ignore)]
        public string AudioQuality { get; set; }

        [JsonProperty("audioSampleRate", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? AudioSampleRate { get; set; }

        [JsonProperty("audioChannels", NullValueHandling = NullValueHandling.Ignore)]
        public long? AudioChannels { get; set; }
    }

    public partial class ColorInfo
    {
        [JsonProperty("primaries")]
        public Primaries Primaries { get; set; }

        [JsonProperty("transferCharacteristics")]
        public TransferCharacteristics TransferCharacteristics { get; set; }

        [JsonProperty("matrixCoefficients")]
        public MatrixCoefficients MatrixCoefficients { get; set; }
    }

    public partial class Range
    {
        [JsonProperty("start")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Start { get; set; }

        [JsonProperty("end")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long End { get; set; }
    }

    public partial class VideoDetails
    {
        [JsonProperty("videoId")]
        public string VideoId { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("lengthSeconds")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long LengthSeconds { get; set; }

        [JsonProperty("keywords")]
        public string[] Keywords { get; set; }

        [JsonProperty("channelId")]
        public string ChannelId { get; set; }

        [JsonProperty("isOwnerViewing")]
        public bool IsOwnerViewing { get; set; }

        [JsonProperty("shortDescription")]
        public string ShortDescription { get; set; }

        [JsonProperty("isCrawlable")]
        public bool IsCrawlable { get; set; }

        [JsonProperty("thumbnail")]
        public WatermarkClass Thumbnail { get; set; }

        [JsonProperty("averageRating")]
        public double AverageRating { get; set; }

        [JsonProperty("allowRatings")]
        public bool AllowRatings { get; set; }

        [JsonProperty("viewCount")]
        public string ViewCount { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("isPrivate")]
        public bool IsPrivate { get; set; }

        [JsonProperty("isUnpluggedCorpus")]
        public bool IsUnpluggedCorpus { get; set; }

        [JsonProperty("isLiveContent")]
        public bool IsLiveContent { get; set; }
    }

    public enum MatrixCoefficients { ColorMatrixCoefficientsBt709 };

    public enum Primaries { ColorPrimariesBt709 };

    public enum TransferCharacteristics { ColorTransferCharacteristicsBt709 };

    public enum ProjectionType { Rectangular };

}
